FROM nginx:stable-alpine

# Ensure that the dependencies is up to date
RUN apk add -Uu --no-cache \
    curl \
    ca-certificates

# https://github.com/socheatsok78/s6-overlay-installer
ARG S6_OVERLAY_VERSION=v3.1.5.0\
    S6_OVERLAY_INSTALLER=main/s6-overlay-installer-minimal.sh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/socheatsok78/s6-overlay-installer/${S6_OVERLAY_INSTALLER})"

ADD rootfs /

ARG S6_VERBOSITY=0
ENV S6_VERBOSITY=${S6_VERBOSITY} \
    S6_BEHAVIOUR_IF_STAGE2_FAILS=2

ENTRYPOINT [ "/init" ]
CMD [ "sleep", "infinity" ]
