name: release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types:
      - "published"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build s6-overlay-nginx-module
        run: |
          make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/s6-overlay-nginx-module.tar.zx
